### ISSUE TITLE
Guild create 

### ISSUE THREAD

**Issue by sysysysy242** [Androz2091/ManageInvite#20]
I've get error wiht i add the bot to my guild : TypeError: Cannot read property 'find' of undefined
    at module.exports.run (D:\Bureau\eaz\invitebot\events\guildCreate.js:17:50)

pls help me

**Comment by Androz2091** [comment]
Hello,
That's weird, did you modify the code?

**Comment by sysysysy242** [comment]
Yeah, a little , i've get the norz code

**Comment by Androz2091** [comment]
Maybe you modified something you shouldn't. I can't give help for forks.

**Comment by sysysysy242** [comment]
oh euu okay
