### ISSUE TITLE
How donfig logs

### ISSUE THREAD

**Issue by sysysysy242** [Androz2091/ManageInvite#21]
Men , sry but , i dont know how config logs :

    addLogs:        "XXXXXXXXXXX",
    removeLogs:     "XXXXXXXXXXX",
    shardLogs:      "XXXXXXXXXXX",
    dashLogs:       "XXXXXXXXXXX",
    statsLogs:      "XXXXXXXXXXX",

How please

**Comment by Androz2091** [comment]
It's the channels IDs.

**Comment by sysysysy242** [comment]
var eventName = msg.name === 'error' ? 'errorMessage' : msg.name
                          ^

TypeError: Cannot read property 'name' of undefined


I get this

**Comment by Androz2091** [comment]
I don't know. Maybe it's because you edited the code...

**Comment by sysysysy242** [comment]
okay , i've download your script , i modifie de config.js ,and i get to this error .

**Comment by Androz2091** [comment]
That's weird. What's your NodeJs version?
