### ISSUE TITLE
this.channel.guild is not a function 

### ISSUE THREAD

**Issue by Alpha3235** [Androz2091/ManageInvite#3]
i am getting this error in the bot 
![Screenshot_2020_0212_115848](https://user-images.githubusercontent.com/43195493/74308825-42869600-4d8f-11ea-842c-a58f73617fa8.png)

**Comment by Androz2091** [comment]
@Alpha3235, try to update your code to the lastest version (run `git pull`)

**Comment by Alpha3235** [comment]
means i have foke the new version of the bot what i update the latest version

**Comment by Alpha3235** [comment]
i have try to host in glitch so i didn't get any error but when i try to host in my vps then i got that error

**Comment by Androz2091** [comment]
run `git pull`
