### ISSUE TITLE
what's mongodb url?

### ISSUE THREAD

**Issue by survvz** [Androz2091/ManageInvite#4]
![EE7FFC3F-090F-43E8-BA7A-747949E846C7](https://user-images.githubusercontent.com/50516938/74641034-82bb8f00-5168-11ea-8d81-779531d071f2.png)

Hey Androz wondering what to put in mongodb and other spaces , thanks

**Comment by Androz2091** [comment]
You can't host a Mongo database on Glitch. Do you have a server for it?

**Comment by survvz** [comment]
> You can't host a Mongo database on Glitch. Do you have a server for it?

yes i do, i have a cluster link...

**Comment by Androz2091** [comment]
So set the config field `mongodb` to your cluster link.
