### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Hadi-koubeissi** [Androz2091/ManageInvite#5]
![Screenshot_٢٠٢٠-٠٢-١٦-٠٩-٤٣-٣٨](https://user-images.githubusercontent.com/42873015/74666547-5e80a200-51aa-11ea-9778-fbb2a2a9042c.png)
![Screenshot_٢٠٢٠-٠٢-١٦-٠٩-٤٣-٣٣](https://user-images.githubusercontent.com/42873015/74666554-62acbf80-51aa-11ea-8613-468a15572905.png)

Hello, can you tell me how to do this and turn on the dashboard? I don’t know what went wrong. I did it with Atlanta and it worked.

**Comment by Androz2091** [comment]
Yes, that's not the same. You must add a redirect url:
`http://144.91.106.236:80/api/callback`
to make it work

**Comment by Hadi-koubeissi** [comment]
Well what is th api

**Comment by Androz2091** [comment]
It's the name of the route, don't modify the link.

**Comment by Hadi-koubeissi** [comment]
![Screenshot_٢٠٢٠-٠٢-١٨-١٧-٤٦-٣٣](https://user-images.githubusercontent.com/42873015/74752026-c13f6f80-5276-11ea-87d9-51ee4668dc5e.png)
![Screenshot_٢٠٢٠-٠٢-١٨-١٧-٤٦-٥١](https://userimages.githubusercontent.com/42873015/74752036-c4d2f680-5276-11ea-876e-ca544f736a43.png)
![Screenshot_٢٠٢٠-٠٢-١٨-١٧-٤٧-٢٦](https://user-images.githubusercontent.com/42873015/74752045-c7cde700-5276-11ea-8a3c-7cdd03145f4d.png)
Not working :(

**Comment by Hadi-koubeissi** [comment]
![Screenshot_٢٠٢٠-٠٢-١٨-١٧-٤٦-٥١](https://user-images.githubusercontent.com/42873015/74752122-e2a05b80-5276-11ea-8afe-e25a381cbf81.png)

**Comment by Androz2091** [comment]
Can you send the full URL? The one here:
<img width="240" alt="Capture d’écran 2020-02-18 à 19 19 43" src="https://user-images.githubusercontent.com/42497995/74765342-aaebe080-5283-11ea-8304-5ef8fd695c51.png">

**Comment by Hadi-koubeissi** [comment]
Yes

**Comment by Hadi-koubeissi** [comment]
https://discordapp.com/oauth2/authorize?client_id=677133625745211444&scope=identify%20guilds&response_type=code&redirect_uri=http%3A%2F%2F144.91.106.236%2Fapi%2Fcallback&state=dcqd7k

**Comment by Androz2091** [comment]
Oh, I see. Update your `baseURL` in the config file and add `:8080` at the end.

**Comment by Hadi-koubeissi** [comment]
Ok ❤

**Comment by Hadi-koubeissi** [comment]
Ohh tkank you is working ❤❤❤❤

**Comment by Hadi-koubeissi** [comment]
Thank you work ❤

**Comment by Hadi-koubeissi** [comment]
shit new error xD
![Screenshot_٢٠٢٠-٠٢-١٨-٢٠-٥١-١٧](https://user-images.githubusercontent.com/42873015/74768077-9f52e680-5290-11ea-912b-79011354efa2.png)

**Comment by Androz2091** [comment]
Yeah, it has been fixed. Update your code and it will work.

**Comment by Hadi-koubeissi** [comment]
Thank you very much for helping me ❤❤❤❤, but I want to ask a question, for example, I wanted to cancel the premium bot from the dashboard and command +add 10 or 30 Or if I also create a premium bot, how do I do that?

**Comment by Androz2091** [comment]
You can't and you won't receive any help for that.
