### ISSUE TITLE
Erreur lors du lancement du bot

### ISSUE THREAD

**Issue by Pronicio** [Androz2091/ManageInvite#57]
Bonjour, j’ai un problème le bot ne veut pas démarrer, j’ai mis la base de données et elle marche voici l’erreur :

![7320A7A8-F3B7-498A-9F9A-D85ED4F1A621](https://user-images.githubusercontent.com/52421988/82213784-06764a80-9915-11ea-859c-40bb57198623.jpeg)

Merci.

**Comment by Androz2091** [comment]
Bonjour,
Actuellement il n'est pas possible d'initialiser la base de données PostgreSQL mais un script `.sql` sera bientôt disponible pour vous permettre de faire tourner ManageInvite sur vos propres serveurs.

**Comment by Pronicio** [comment]
D’accord, merci de votre réponse rapide.
