### ISSUE TITLE
guild.roles.cache.find

### ISSUE THREAD

**Issue by Hadi-koubeissi** [Androz2091/ManageInvite#6]
Hello how are you there is a problem when you specify his rank you take it when you invite someone and go to the dashboard you do not work with me thank you
![Screenshot_٢٠٢٠-٠٢-٢٠-١٦-٠٩-١٦](https://user-images.githubusercontent.com/42873015/74941514-d2fe4f80-53fb-11ea-8ec2-5a0b44c4e161.png)

**Comment by mystere19052003** [comment]
Hello, can you send the whole error please?

**Comment by Hadi-koubeissi** [comment]
Yes ❤❤

https://pastebin.com/p8L0s0hj

**Comment by Androz2091** [comment]
Will be fixed as soon as I can.

**Comment by Hadi-koubeissi** [comment]
Ok thank you ❤

**Comment by Hadi-koubeissi** [comment]
Hello again there is also this error when I activate the welcome or departure command and choose a message and then write the command + config get me this error
![Screenshot_٢٠٢٠-٠٢-٢١-١٧-١٠-١١](https://user-images.githubusercontent.com/42873015/75046208-59cf2d00-54cd-11ea-8ffb-a755176c14d8.png)

**Comment by Androz2091** [comment]
Will also be fixed. Thank you

**Comment by Hadi-koubeissi** [comment]
No problem, you are welcome

**Comment by Androz2091** [comment]
Fixed

**Comment by Hadi-koubeissi** [comment]
Ok thank you ❤
