### ISSUE TITLE
Low quality software product

### ISSUE THREAD

**Issue by Julien00859** [Androz2091/ManageInvite#71]
Hello,

I had a look at the commit history and was outraged by the amount of commits fixing bugs. I had a look at the commit themselves, are you seriously fixing missing await ? I couldn't find any automated test suit or unittest and I think you don't even test your product yourself.

Just you know, no commit should introduce any bug. A commit is the minimum version value of a software so no commit should land on the master branch without proper testing.

What is the benefit to have separated develop and master branches if there is no serious quality insurance done before merging develop into master ??

I see you are using some automated tools to validate PRs, explain me how they could let such syntax error pass ? https://github.com/Androz2091/ManageInvite/pull/43/files

You shouldn't be glad to serve several thousand users with such low quality product. I ought you to consider a plan to introduce a systematic testing plan and to aim to reach a bare minimum of 60% testing coverage.

* https://en.wikipedia.org/wiki/Extreme_programming
* https://en.wikipedia.org/wiki/Unit_testing
* https://en.wikipedia.org/wiki/Test-driven_development

Although this issue seems very aggressive, my aim is to better the overall software quality product of open-source projects, as software developer it is your responsibility to deliver working product. Users don't want bugfixes, they want features, please ensure the several features you deliver are bugfree beforehand, this will increase your overall productivity (no time lost fixing bugs) and increase the confidence your users have toward your project. Also having both "test: pass" and "code coverage: 80%" badges in the readme is something all developers love :stuck_out_tongue: 

Regards,

**Comment by Androz2091** [comment]
Hello, @Julien00859,
Thank you, we take note of your suggestions in order to improve the development of ManageInvite in the future.
Sincerely,
Androz.
