### ISSUE TITLE
Staff member

### ISSUE THREAD

**Issue by HideakiAtsuyo** [Androz2091/ManageInvite#77]
https://github.com/Androz2091/ManageInvite/commit/fd40941f873c0c6eae59d449f89a66f9c9e8ced9

J'aimerais savoir à quoi ça sert exactement ce commit m'a étonné, en gros une personne étant dans ce tableau(ayant son id dedans) peut arriver sur le serveur et modifier les paramètres etc...?

**Comment by Androz2091** [comment]
Bonjour
Toutes les informations sur la hiérarchie des permissions sont dans le fichier `helpers/permissions.js`. Certains modérateurs du bot sont donc autorisés à effectuer les commandes de configuration des serveurs (utile quand un utilisateur a besoin d'aide).

**Comment by HideakiAtsuyo** [comment]
Dans ce cas je suggère l'ajout d'un paramètre qui serait fait pour les autoriser ou non, autoriser les modérateurs du bots à exécuter les commandes ou non, par défaut la valeur serait négative, car je ne trouve pas la chose très sécurisée 🤷

**Comment by Androz2091** [comment]
Pour ceux qui souhaitent installer le bot, libre à vous de ne définir aucun modérateur. Pour la version en ligne, les modérateurs qui ont besoin des permissions passent d'abord une phase de test avant de les obtenir. Je ne vais pas plus m'attarder sur cette question, je préfère avoir peu de membres du staff de confiance que de nombreux membres auxquels je ne peux pas assez faire confiance pour leurs donner ces permissions.

**Comment by HideakiAtsuyo** [comment]
D'accord je vois merci pour les réponses apportées :)
